Update sccache to 0.7.2 so that we get nvc++ support
rapidsai/devcontainers pull request #177
Opened 2023-11-16 14:21 UTC by miscco

2023-11-16 17:28 UTC, trxcllnt approved these changes

2023-11-16 17:29 UTC, trxcllnt requested changes
Also bump the version in `sccache/devcontainer-feature.json`

2023-11-16 18:36 UTC, trxcllnt approved these changes

2023-12-09 16:26 UTC, bdice commented
FYI: we're updating RAPIDS CI images to sccache 0.7.4 here: https://github.com/rapidsai/ci-imgs/pull/97

Maybe we can align on that version and merge this to 24.02?

2023-12-12 18:02 UTC, merged

2023-12-12 18:18 UTC, bdice commented
@trxcllnt This was merged to 23.12. Do we have forward mergers set up for `branch-24.02`? Can we work with ops to get those set up?