Remove nx-cugraph from cugraph
rapidsai/devcontainers pull request #418
Opened 2024-11-14 02:23 UTC by eriknw

I believe this is needed to remove `nx-cugraph` from the `cugraph` repo being done in https://github.com/rapidsai/cugraph/pull/4756

This is a subset of the changes @jameslamb is making in https://github.com/rapidsai/devcontainers/pull/417. Does it make sense to do this change for `nx-cugraph` and `cugraph-gnn` independently (how close is `cugraph-gnn` to being removed?)? Should we also add `nx-cugraph` as done in that PR? Anything else?

@nv-rliu @jameslamb @rlratzel

2024-11-14 14:43 UTC, jameslamb requested changes
This is not the right fix. Don't you still want `nx-cugraph` to be buildable with devcontainers? Even if we don't add devcontainer CI / devcontainer configs in the https://github.com/rapidsai/nx-cugraph repo, I think it'd still be useful to have that support here in the unified devcontainer... so you could make a change in cugraph and then test how it affects nx-cugraph.

That is why in #417, I *added* something like this:

```yaml
- name: nx-cugraph
  path: nx-cugraph
  git: {<<: *git_defaults, repo: nx-cugraph}
  python:
    - name: nx-cugraph
      sub_dir: .
      args: {install: *rapids_build_backend_args}
```

And please see the other change there... any time you change the content of something in `features/` here, you need to bump it's version.

<img width="679" alt="image" src="https://github.com/user-attachments/assets/7c3c1077-645e-4d2c-a7b2-8d7062212eed">

Once those are addressed, I support moving this PR forward and not trying to wait on the GNN projects. I'd hoped to be able to do this all at once, but `cugraph-gnn` needs a bit more work.

2024-11-14 14:45 UTC, jameslamb commented
Also note that the CI failures here weren't because of your changes, and should resolve on a re-run now that https://github.com/rapidsai/raft/pull/2490 was merged.

2024-11-14 16:25 UTC, eriknw commented
Thanks @jameslamb I suspected we needed to make those changes, thanks for explaining :) . Updated.

2024-11-14 16:57 UTC, trxcllnt commented
> @jameslamb Even if we don't add devcontainer CI / devcontainer configs in the [nx-cugraph](https://github.com/rapidsai/) repo

We should add devcontainers to the new nx-cugraph repo. Aside from them being a convenient way to work on a project for outside contributors, they also help ensure nx-cugraph changes don't break devcontainer and DLFW builds.

2024-11-14 17:12 UTC, jameslamb commented
> We should add devcontainers to the new nx-cugraph repo

Great, let's do that. Want to put up a PR at https://github.com/rapidsai/nx-cugraph?

2024-11-14 19:02 UTC, jameslamb commented
Believe CI errors like this:

```text
/home/coder/cuvs/cpp/src/neighbors/iface/iface.hpp(176): error: incomplete type is not allowed

1 error detected in the compilation of "/home/coder/cuvs/cpp/src/neighbors/iface/iface_cagra_float_uint32_t.cu".
```

([build link](https://github.com/rapidsai/devcontainers/actions/runs/11841308604/job/32997252347?pr=418))

Should be fixed by https://github.com/rapidsai/cuvs/pull/467

2024-11-14 22:55 UTC, jameslamb commented
I put up a PR to add devcontainers CI jobs for `nx-cugraph`: https://github.com/rapidsai/nx-cugraph/pull/25

2024-11-15 05:01 UTC, jameslamb approved these changes

2024-11-15 15:27 UTC, jameslamb commented
Even though this change is also covered in #417, CI just started over there and takes a couple hours to run.

Merging this to unblock https://github.com/rapidsai/cugraph/pull/4756 and https://github.com/rapidsai/nx-cugraph/pull/25

2024-11-15 15:27 UTC, merged